### ISSUE TITLE
Ayuda con Doble titulación

### ISSUE THREAD

**Issue by waio1990** [FCFM-ADI/memoria-latex#6]
Hola, necesito ayuda para incluir la doble titulación en mi portada. Dado que solo aparece una carrera, no estoy seguro de como incluir una segunda, necesito que diga:

Tesis para Optar al Grado de Magister en economia aplicada
Memoria para optar al Grado e Ingeniero Civil Industrial

He modificado un poco el template (necesitaba que estuviera en ingles), pero no pillo una opción para agregar la doble titulación

Saludos y gracias!

**Comment by badgercl** [comment]
Hola, 

Para doble titulación puedes hacer lo siguiente:
1. Comenta el tag de carrera con %
2. En \memoria pone las 2 memorias separadas de un \newline

Debería quedar algo así
`%\carrera{Nombre de la carrera}
\memoria{Tesis para Optar al Grado de Magister en economia aplicada \newline Memoria para optar al Grado e Ingeniero Civil Industrial}`

De ese modo se forma la portada con los 2 títulos que necesitas.
Coméntanos si esta solución te sirve.

Por otro lado, si nos envías la adaptación al inglés la podríamos incluir en el Zip con los templates para que otra gente lo pueda usar en el futuro 😃
