### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by fmontoto** [FCFM-ADI/memoria-latex#7]
Hola, alguna posibilidad de agregar una licencia a la plantilla?

**Comment by badgercl** [comment]
Hola,

A qué te refieres con la licencia, ¿estilo Creative Commons?
¿Donde pretendes agregarla?

La plantilla ofrecida sigue los lineamientos que entrega Biblioteca Central, que están disponibles en la web de Títulos y Grados. Salirse de estos lineamientos puede provocar retrasos en la titulación producto de observaciones que biblioteca genere. 

Si tienes claro donde quieres agregar la licencia, te recomendamos que corrobores en biblioteca central si es aceptable. Si es así, podrías enviarnos el pull request. Así lo agregaríamos al template y ofreceríamos la opción de seleccionar una lista de licencias a seleccionar.

De todos modos, al momento de subir tu memoria a cybertesis, se te pregunta qué tipo de Creative Commons utilizarás, pero quedará como metadato y no se reflejará en el PDF final.

**Comment by fmontoto** [comment]
Una licencia para el código en el repositorio, no que aparezca en el documento generado. Para usar libremente el repositorio.

**Comment by badgercl** [comment]
¿Esto? https://github.com/FCFM-ADI/memoria-latex/blob/master/LICENSE
(btw, lo agregamos recién)

**Comment by fmontoto** [comment]
jajaja gracias!
