### ISSUE TITLE
Algunos pequeños problemas con la clase umemoria

### ISSUE THREAD

**Issue by NachoCorreaFalconi** [FCFM-ADI/memoria-latex#8]
Estimadas y estimados,

He notado algunos problemas pequeños con respecto a la clase umemoria. Doy mi retroalimentación para que éstos puedan ser resueltos:

1) En la línea 44 del archivo `umemoria.cls` se redefine el nombre del Índice a Tabla de Contenidos. Según la Pauta para la normalización de Tesis (v6, la que viene adjunta en ucampus) el nombre debe ser Tabla de Contenido. He sabido de gente a la cual ese detalle le fue corregido.

2) Descubrí un pequeño bug (?) cuando se usa la opción `oneside` en el comando `\documentclass`. Si la opción `oneside` no se usa, al compilar y abrir el `.pdf` (en Acrobat Reader, por ejemplo) las páginas están bien numeradas con respecto al contador de páginas de Reader (no me refiero a lo que aparece en la página _per se_, sino que al contador que aparece en la barra de opciones de Reader) (en numerales romanos al comienzo y luego con números naturales). Sin embargo, cuando la opción `oneside` se ocupa, ocurre el siguiente problema: la portada y el resumen ejecutivo están numerados con el mismo numeral romano i. Esto causa que a la hora de imprimir el trabajo el resumen ejecutivo no sea impreso (considerando que la portada debe imprimirse a color y el resumen no).
Una solución para esto es añadir en el preámbulo los siguientes comandos:
`\makeatletter`
`\g@addto@macro\titlepage{\pagenumbering{Alph}}`
`\g@addto@macro\endtitlepage{\pagenumbering{roman}}`
`\makeatother`
Básicamente esos comandos hacen que la portada esté numerada con una letra A. El problema ocurre porque el macro `\frontmatter` usa `\pagenumbering{roman}` al final, que hace que la numeración sea en romanos y resetea el contador de páginas al final; el ambiente `titlepage` sólo resetea el contador de páginas en su final. Un último detalle es que no es conveniente usar `\makeatletter` y `\makeatother` ni en paquetes `.sty` ni en clases `.cls` ([referencia](http://tex.stackexchange.com/questions/62583/is-it-really-bad-to-use-makeatletter-and-makeatother-in-a-package-or-class-fil)).
No sé si ocurre en todas las carreras, pero sé de algunas que piden que los trabajos sean impresos por una plana, y la opción `oneside` es _ad hoc_ para que la impresión se vea mejor. ¿Se podrá confirmar cuál es la forma oficial de impresión para todas las carreras, para así tener en cuenta este pequeño detalle?

Saludos y muchas gracias de antemano.

**Comment by badgercl** [comment]
Hola,

El problema (1) esta ya arreglado, ¡gracias!

Respecto a (2) efectivamente en Acrobat no es posible imprimir sólo la página de resumen en las condiciones que nos indicas. Sobre que la página de resumen debe imprimirse en blanco y negro, debe ser una regla de tu departamento ya que en la Pauta de Normalización de Memorias, disponible en la sección de Títulos y Grados, de donde sacaste el template de la memoria, no hay mención sobre que deba ser forzadamente así. 
De todos modos incluimos tu fix. Gracias!
